//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProject.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.StudentInfoSOAPSoap")]
    public interface StudentInfoSOAPSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AddNewStudent(string name, int age, int course, string Class, double AvrgMark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddNewStudentAsync(string name, int age, int course, string Class, double AvrgMark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllStudents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ShowAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ShowAllStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RemoveStudent(int StudentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RemoveStudentAsync(int StudentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/refresh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int refresh(int StudentID, string name, int age, int course, string Class, double AvrgMark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/refresh", ReplyAction="*")]
        System.Threading.Tasks.Task<int> refreshAsync(int StudentID, string name, int age, int course, string Class, double AvrgMark);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentInfoSOAPSoapChannel : ClientProject.ServiceReference2.StudentInfoSOAPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentInfoSOAPSoapClient : System.ServiceModel.ClientBase<ClientProject.ServiceReference2.StudentInfoSOAPSoap>, ClientProject.ServiceReference2.StudentInfoSOAPSoap {
        
        public StudentInfoSOAPSoapClient() {
        }
        
        public StudentInfoSOAPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentInfoSOAPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentInfoSOAPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentInfoSOAPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddNewStudent(string name, int age, int course, string Class, double AvrgMark) {
            return base.Channel.AddNewStudent(name, age, course, Class, AvrgMark);
        }
        
        public System.Threading.Tasks.Task<int> AddNewStudentAsync(string name, int age, int course, string Class, double AvrgMark) {
            return base.Channel.AddNewStudentAsync(name, age, course, Class, AvrgMark);
        }
        
        public System.Data.DataTable ShowAllStudents() {
            return base.Channel.ShowAllStudents();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ShowAllStudentsAsync() {
            return base.Channel.ShowAllStudentsAsync();
        }
        
        public int RemoveStudent(int StudentID) {
            return base.Channel.RemoveStudent(StudentID);
        }
        
        public System.Threading.Tasks.Task<int> RemoveStudentAsync(int StudentID) {
            return base.Channel.RemoveStudentAsync(StudentID);
        }
        
        public int refresh(int StudentID, string name, int age, int course, string Class, double AvrgMark) {
            return base.Channel.refresh(StudentID, name, age, course, Class, AvrgMark);
        }
        
        public System.Threading.Tasks.Task<int> refreshAsync(int StudentID, string name, int age, int course, string Class, double AvrgMark) {
            return base.Channel.refreshAsync(StudentID, name, age, course, Class, AvrgMark);
        }
    }
}
